name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.6
  - numpy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - matplotlib    
    - geopy
    - shapely
    - geographiclib
